### ISSUE TITLE
没有图标？

### ISSUE THREAD

**Issue by woodvillage** [jamasBian/youdao-note-electron#1]
ctrl-tab的时候也看不到

**Comment by woodvillage** [comment]
重新打开了一次有图标了...

**Comment by woodvillage** [comment]
是用cef做的么，默认开了那个开发者窗口...

**Comment by jamasBian** [comment]
electron做的，默认应该没开开发者窗口。
图标这边不太稳定。
之前用ubuntu，不确定其他能否正常显示图标。
如果有兴趣可以帮忙做一下。

**Comment by jamasBian** [comment]
解决图标的问题。
cp ./assets/icon.png ./node_modules/_electron@1.4.15@electron/dist/resources/
