### ISSUE TITLE
打包好的linux版本如何快捷打开？

### ISSUE THREAD

**Issue by 1049451037** [jamasBian/youdao-note-electron#11]
每次都要先cd到那个目录，然后打开终端，然后运行Youdao-Note-Electron，太繁琐了，请问有简便的方法吗？

**Comment by ace-astra** [comment]
你可以自己写个.desktop文件，扔到 ~/.local/share/applications/ 目录下面

**Comment by 1049451037** [comment]
好的，谢谢～
